# Change these first
owner: kuhnfelix18052005 # Your GitHub organization or username, where this repository lives
repo: EE2Uptime # The name of this repository

sites:
  - name: SMS
    url: https://sms.eursc.eu
  - name: STS Login Page
    url: https://sts.eursc.eu/adfs/ls/
  - name: Office365
    url: https://www.office.com
  - name: Microsoft Teams
    url: https://teams.microsoft.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: pupilscom-mamer.eu
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://pupilscom-mamer.eu/wp-content/uploads/2021/06/European_School_of_Luxembourg_II_school_and_pupils_committee_PC_logo.jpg
  name: ESL2 Status Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/kuhnfelix18052005/EE2Uptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kuhnfelix18052005/EE2Uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
